//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class custumer_historys_tbl
    {
        public int CustumerHistorysID { get; set; }
        public int IDFromShop { get; set; }
        public int IDfromUser { get; set; }
        public int NumOfTimeGoToShope { get; set; }
        public int NumOfTimeWasSatified { get; set; }
    
        public virtual shops_tbl shops_tbl { get; set; }
        public virtual custumers_tbl custumers_tbl { get; set; }
    }
}
