//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<audiences_tbl> audiences_tbl { get; set; }
        public virtual DbSet<categorys_in_shop> categorys_in_shop { get; set; }
        public virtual DbSet<categorys_tbl> categorys_tbl { get; set; }
        public virtual DbSet<custumer_historys_tbl> custumer_historys_tbl { get; set; }
        public virtual DbSet<custumers_tbl> custumers_tbl { get; set; }
        public virtual DbSet<malls_tbl> malls_tbl { get; set; }
        public virtual DbSet<shops_tbl> shops_tbl { get; set; }
        public virtual DbSet<shopsInMall_tbl> shopsInMall_tbl { get; set; }
    }
}
