//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class shopsInMall_tbl
    {
        public int shopInMallID { get; set; }
        public int IdFromMall { get; set; }
        public int IdFromShop { get; set; }
    
        public virtual malls_tbl malls_tbl { get; set; }
        public virtual shops_tbl shops_tbl { get; set; }
    }
}
