//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalLocation_App.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MalLocationDBEntities : DbContext
    {
        public MalLocationDBEntities()
            : base("name=MalLocationDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<audiences_tbl> audiences_tbl { get; set; }
        public virtual DbSet<categorys_tbl> categorys_tbl { get; set; }
        public virtual DbSet<custumers_tbl> custumers_tbl { get; set; }
        public virtual DbSet<malls_tbl> malls_tbl { get; set; }
        public virtual DbSet<shops_tbl> shops_tbl { get; set; }
    }
}
