//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalLocation_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shops_tbl
    {
        public int ShopID { get; set; }
        public string ShopName { get; set; }
        public Nullable<int> IdFromAudience { get; set; }
    
        public virtual audiences_tbl audiences_tbl { get; set; }
    }
}
