//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class categorys_in_shop
    {
        public int categoryInShopID { get; set; }
        public Nullable<int> IdFromCategory { get; set; }
        public Nullable<int> IdFromShop { get; set; }
    
        public virtual categorys_tbl categorys_tbl { get; set; }
        public virtual shops_tbl shops_tbl { get; set; }
    }
}
